# Generated by Django 4.2.21 on 2025-06-04 01:30

import core.shared.Upload_to
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='majority',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='decision',
            name='quorum',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='decision',
            name='resolution',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='decision',
            name='tags',
            field=models.CharField(blank=True, db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='itemattachment',
            name='file',
            field=models.FileField(upload_to=core.shared.Upload_to.upload_to),
        ),
    ]
