# Generated by Django 4.2.21 on 2025-06-06 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_activity_created_by_alter_activity_creator_and_more'),
    ]

    operations = [
    ]
