# Generated by Django 4.2.21 on 2025-06-06 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20250606_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='reviewer',
            field=models.ForeignKey(blank=True, help_text='Person reviewing this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tasks', to=settings.AUTH_USER_MODEL, to_field='uid'),
        ),
        migrations.AlterField(
            model_name='itemattachment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='uid'),
        ),
    ]
