# Generated by Django 4.2.21 on 2025-06-06 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_alter_activity_reviewer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who created the task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='creator',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='next_responsible',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_next_responsible_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Primary owner of the task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='previous',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_superseded_by', to='core.activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='responsible',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_responsible_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='reviewer',
            field=models.ForeignKey(blank=True, help_text='Person reviewing this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated the task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='brief',
            name='creator',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='brief',
            name='next_responsible',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_next_responsible_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='brief',
            name='responsible',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_responsible_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='decision',
            name='creator',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='decision',
            name='next_responsible',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_next_responsible_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='decision',
            name='previous',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_superseded_by', to='core.decision'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='responsible',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_responsible_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemattachment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='responsibilityqueue',
            name='assigned_to',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
