# Generated by Django 4.2.21 on 2025-06-06 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_activity_created_by_alter_activity_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='adopted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
