# Generated by Django 4.2.21 on 2025-06-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_activity_uid_alter_brief_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='referenced_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='brief',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='brief',
            name='referenced_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='brief',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='decision',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='decision',
            name='referenced_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='decision',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
