# Generated by Django 4.2.21 on 2025-06-06 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.group', to_field='uid'),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL, to_field='uid'),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Default code = default ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='users', to='accounts.subscriptiontype',  verbose_name='Subscription type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='useracceptlist',
            name='accepted_user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='accepted_by_users', to=settings.AUTH_USER_MODEL, to_field='uid'),
        ),
        migrations.AlterField(
            model_name='useracceptlist',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='accepted_users', to=settings.AUTH_USER_MODEL, to_field='uid'),
        ),
        migrations.AlterField(
            model_name='userblocklist',
            name='blocked_user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blocked_by_users', to=settings.AUTH_USER_MODEL, to_field='uid'),
        ),
        migrations.AlterField(
            model_name='userblocklist',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blocked_users', to=settings.AUTH_USER_MODEL, to_field='uid'),
        ),
    ]
