# Generated by Django 4.2.21 on 2025-06-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_group_groupmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_out_of_office',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='out_of_office_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
